version: '3.9'
services:

  db:
    image: postgres:14
    container_name: don-t_psql
    env_file: db.env
    networks:
      db_net:
        ipv4_address: 172.19.0.2
    ports: 
      - 5432:5423 
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:

networks:
  db_net:
    ipam:
        driver: default
        config:
          - subnet: "172.19.0.0/24"