version: '3.9'
services:

  db:
    image: postgres:14
    container_name: cryptual_psql
    env_file: db.env
    networks:
      db_net:
        ipv4_address: 172.19.0.1
    ports: 
      - 5432:5423
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:

networks:
  db_net:
    ipam:
        driver: default
        config:
          - subnet: "172.19.0.0/24"